---
title: "Resumen metaanálisis"
author: "Roxana Andreea Moldovan Moldovan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
    toc_float: false
    number_sections: false 
    code_folding: hide
    theme: flatly
    bg: '#FFFFFF'
    fg: '#202020'
    primary: '#90C432'
    secondary: '#2494b5' 
  pdf_document:
    extra_dependencies: "subfig"
linkcolor: blue
urlcolor: blue
citecolor: blue
header-includes:
- \usepackage{subfig}
- \usepackage{float}
fig_caption: yes 
link-citations: TRUE

---

```{r setup, include=FALSE}
doAll = F
showAll = T
centrado = "center"
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=T, eval=TRUE, message=FALSE, warning=FALSE}
library(pacman)
pacman::p_load(clusterProfiler)
pacman::p_load(dplyr)
pacman::p_load(glue)
pacman::p_load(org.Hs.eg.db)
pacman::p_load(parallel)
pacman::p_load(ReactomePA)
pacman::p_load(stringr)
pacman::p_load(sf)
pacman::p_load(flextable)
pacman::p_load(officer)
pacman::p_load(ggVennDiagram)
pacman::p_load(ggplot2)

## Parametros
DirBase = "/home/rmoldovan/Metaanalisis"
DirBase = "C:/Users/roxya/OneDrive/Documentos/01Master_bioinformatica/00TFM/Git/T2D-Meta-Analysis"
DirData = glue("{DirBase}/Data")
DirPlots =  glue("{DirBase}/Plots")
DirOut = glue("{DirData}/FA")

## Carga de funciones
#source(glue("{DirBase}/02Scripts/Functions.R"))

```

```{r echo=T, eval=TRUE, message=FALSE, warning=FALSE}  
# Function
# Output table
RX_table <- function(Data,
                     Color1 = "#007FA6",
                     Color2 = "#007FA6" ,
                     Color.l = "black" ,
                     Color.l2 = "#878787",
                     Color.up = "#CB326D",
                     Color.down = "#00AFBB",
                     footer = NULL,
                     font = "Calibri"){
  cols=colnames(Data)[-c(1)] # Columns with info
  col_keys = colnames(Data) # Nombres unicos de las columnas
  # Header
  header = data.frame(col_keys = col_keys,
                      H1 = c("", rep("Contraste", length(cols))),
                      H2 = c("", cols)
                      )
  
  ## Flextable
  # Set info
  ft <- flextable(Data, col_keys = colnames(Data))
  # Set header
  ft <- set_header_df(ft, mapping = header, key = "col_keys" )
  # Format number
  ft <- colformat_num(ft, big.mark = ".", decimal.mark = "," )
  # Set footer
  if(! is.null(footer)){
    ft <- add_footer(ft, values = footer) %>% 
      merge_h(part = "footer")  %>% 
      bold(j=1, part = "footer") %>%
      hline(border = fp_border(width = 2, color = Color1), part = "footer")
  }
  
  # Merge headers
  ft <- merge_h(ft, part = "header") %>% 
    merge_v( part = "header")
  
  # Merge contrastes
  #ft <- merge_v(ft, j = c(1,2), part = "body")
  
  # Horizontal lines
  'ft <- hline(ft, i=seq(from=3, to=nrow(Data), by=3),
              border = fp_border(width = 1, color = Color.l2), part="body")'
  ft <- hline(ft,border = fp_border(width = 2, color = Color1), part = "header")
  
  # Outer bottom
  ft <- hline_bottom(ft, border = fp_border(width = 2, color = Color1))
  
  # Alineamiento
  ft <- flextable::align(ft, i=1, align = "center", part = "header") %>%
    flextable::align(i=2, align = "right", part = "header")
  ft <- flextable::align(ft, align = "right", part = "footer")
  ft <- flextable::align(ft, j=1, align = "left", part = "footer")
  
  
  # Header design
  ft <- fontsize(ft, i = 1:2, size = 12, part = "header") %>%
    color(i=1, color = Color2, part = "header") %>%
    color(i=2, color = Color.l2, part = "header") %>%
    bold(i=1, bold = TRUE, part = "header")
  # Rotate names
  #ft <- rotate(ft, i = 2, rotation = "btlr", part = "header", align = "bottom")
  
  # Font
  #font(ft, fontname = font, part = "all")
  
  # Matriz de colores
  colormatrix <- ifelse(Data[, cols] == 0, Color.l2, Color.l )
  # Color
  ft <- color(ft, j=cols, color = colormatrix, part = "body") 
  # Color
  x = Data[, 1]
  colors = case_when(
    x == "Up" ~ Color.up,
    x == "Down" ~ Color.down,
    TRUE ~ Color.l
  )
  ft <- color(ft, j=1, color = colors, part = "body") %>%
    bold(j=1, bold = TRUE, part = "body")

  return(ft)
}


RX_venn <- function(lists, colors, names){
  venn <- Venn(lists)
  d <- process_data(venn)
  d2 <- process_data(venn)
  
  d2@region <- st_polygonize(d@setEdge) 
  ggplot() +
  geom_sf(aes(fill = name), data = venn_region(d2)) +
  geom_sf(#aes(color = name), 
    size = 4, color = "grey",
    data = venn_setedge(d))  +
  geom_sf_text(aes(label = count), data = venn_region(d)) +
  scale_fill_manual(values = alpha(colors, .3)) +
  theme_void() +  # Tema
        theme(plot.background = element_rect(fill="transparent", color="transparent"),
              panel.background = element_rect(fill = "transparent", color="transparent"),
              axis.line = element_line(colour = "transparent")) +
    guides(fill = guide_legend(title = "Contrastes",
                                order = 1)) +
  if(! is.null(names)){
      geom_sf_text(aes(label = name), data = venn_setlabel(d), nudge_x = -0.1, nudge_y = -0.1) 
  }
  } 
```  


## Obesidad {.tabset .tabset-fade -}   

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE}
# Order
ord = c("Ob_IS.M - Np_IS.M", "Ob_IS - Np_IS", "Ob_IS.F - Np_IS.F", "(Ob_IS.M - Np_IS.M) - (Ob_IS.F-  Np_IS.F)") 
colors = c( "Ob_IS - Np_IS" = "#884EA0",  "Ob_IS.M - Np_IS.M"  = "#2494B5" ,  
            "Ob_IS.F - Np_IS.F" = "#90C432" , "(Ob_IS.M - Np_IS.M) - (Ob_IS.F-  Np_IS.F)" = "#D8609A")
```

### Genes {.tabset .tabset-fade -} 

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE}
DirData = "C:/Users/roxya/OneDrive/Documentos/01Master_bioinformatica/00TFM/Git/T2D-Meta-Analysis/Data/MA/Obesity"

f= c("ObvsNp/Meta-analysis_1_DF.RData", 
     "ObMvsNpM/Meta-analysis_2_DF.RData",
     "ObFvsNpF/Meta-analysis_3_DF.RData",
     "ObM_NpMvsObF_NpF/Meta-analysis_4_DF.RData")

files = glue("{DirData}/{f}")
Datas = sapply(files, function(x) get(load(file=x)), simplify = FALSE)
```

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE}
# Prepare data
p_lim = 0.05
logFC_lim = 0

# Gene lists
Direction = c("Up", "Down")

Data0 = sapply(Datas, function(Data){
  Up = rownames(Data[which(Data$p.adjust.BH < p_lim & Data$logFC > logFC_lim), ])
  Down = rownames(Data[which(Data$p.adjust.BH < p_lim & Data$logFC < 0), ])
  return(c("Up" = list(Up), "Down" = list(Down)))
}, simplify = FALSE)

contrasts = c("Ob - Np", "Ob.M - Np.M", "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
names(Data0) = contrasts
```  

```{r}
library(ComplexHeatmap)
library(ComplexUpset)
ColorList = c("#cef587", "#90C432", "#2494b5","#03556e"  )
ColorPal <- colorRampPalette(ColorList)
Estudios = c("E_MEXP_1425",
             "GSE2508",
             "GSE20950",
             "GSE29718", 
             "GSE64567",
             "GSE78721",
             "GSE92405",
             "GSE141432",
             "GSE205668")
colores = ColorPal(length(ncol(Data)))
AnotDatas = glue("{Estudios}_finalData")
MinSize = 0
An = unlist(Data0, recursive = FALSE) 
An = ComplexHeatmap::list_to_matrix(An) 
Data = data.frame(An)

# Leyenda:
#Anots = as.data.frame(make_comb_mat(An)) 
#Leg = sapply(as.list(Anots), function(x) colnames(Data)[which(x == 1)], simplify = FALSE)
Inter = upset_data(Data,colnames(Data), min_size = MinSize)
Inter= str_split(names(Inter$sizes$exclusive_intersection), pattern = "-")
Leyenda = lapply(Inter, function(x) upset_query(intersect= x,
                                                color=colores[length(x)],
                                                fill=colores[length(x)],
                                                only_components=c('intersections_matrix', 'Intersection size')))

UpsetPlot <- upset(Data, colnames(Data), name = "Intersecciones", guides = "keep",
                   # Numero de interacciones minimas 
                   min_size =10,
    width_ratio=0.16,
    stripes='transparent',
    matrix = intersection_matrix(
            geom=geom_point(
                shape='square',
                size=5,
                stroke = 1
            ), 
            segment=geom_segment(
              size= 1.2
            ),
            outline_color=list(
                active='black',
                inactive='gray'
            )) #+ theme(text=element_text(size = 29,angle=0))
    ,
    # Asignacion de colores
     queries= Leyenda, 
    # Set sizes
    set_sizes = upset_set_size(position='right') 
    # Numero de conteos
    + geom_text(aes(label=..count..), hjust=1.1, stat='count', color="white")
        + ylab('Nº de genes anotados') + theme(axis.text.x=element_text(size = 10,
                                                                  angle=0),
                                               text = element_text(size=15),
                                         panel.grid.minor = element_blank(),
                                         panel.grid.major = element_blank(),
                                         axis.line.x = element_line(color="black"),
                                         axis.ticks = element_line(color="black")),
    # Interactions
    base_annotations = list(
        'Intersection size'=( 
            intersection_size(
              mapping=aes(fill='black'),
              text = list(
                vjust=0.5,
                hjust=-0.2,
                angle=90,
                size =4.5
            ), 
            text_colors=c(
                on_background='black', on_bar='white'
            )
            ) #+ scale_fill_manual(values=c('bars_color'='blue'))   
            + theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank(),
               plot.background = element_rect(fill="transparent",
                                                   color = "transparent"),
          panel.background = element_rect(fill = "transparent",
                                          color = "transparent"),
          axis.line.y = element_line(color="black"),
          axis.text.y=element_text(size = 10, angle=0)
          #axis.line.x = element_line(color="black"),
          #axis.ticks = element_line(color="black")
          )
            + ylab('Anotaciones por grupo')
        )), 
    themes=upset_modify_themes(
        list(
            'intersections_matrix'=theme(text=element_text(size=15)),
            'Intersection size'=theme(text=element_text(size=15)) )
        ) 
) 

# Guardamos 

UpsetPlot
```

```{r}
library(ComplexHeatmap)
library(ComplexUpset) 
MinSize = 0
An = unlist(Data0, recursive = FALSE) 
An = ComplexHeatmap::list_to_matrix(An) 
Data = data.frame(An)

Direction = data.frame(set = colnames(Data),
                       dir = rep(c("Up", "Down"), 4))

# Leyenda:
#Anots = as.data.frame(make_comb_mat(An)) 
#Leg = sapply(as.list(Anots), function(x) colnames(Data)[which(x == 1)], simplify = FALSE)
Inter = upset_data(Data,colnames(Data), min_size = MinSize)
Inter= str_split(names(Inter$sizes$exclusive_intersection), pattern = "-")
Leyenda = lapply(Inter, function(x) upset_query(intersect= x,
                                                color=colores[length(x)],
                                                fill=colores[length(x)],
                                                only_components=c('intersections_matrix', 'Intersection size')))

UpsetPlot <- upset(Data, colnames(Data), name = "Intersecciones", guides = "keep",
                   # Numero de interacciones minimas 
                   min_size =0,
    width_ratio=0.25,
    #stripes='transparent',
    # Sección horizontal
    stripes = upset_stripes(
      mapping=aes(color= dir),
      colors = c(
        "Up"="#CB326D",
        "Down" = "#00AFBB"
      ),
      data = Direction
    ),
    matrix = intersection_matrix(
            geom=geom_point(
                shape='square',
                size=4,
                stroke = 1
            ), 
            segment=geom_segment(
              size= 1.2
            ),
            outline_color=list(
                active='black',
                inactive='gray'
            )), #+ theme(text=element_text(size = 29,angle=0))
    # Cambiamos la posición del set size
    set_sizes = upset_set_size(position='right') + geom_text(aes(label=..count..), hjust=1.1, stat='count', color="white")
        + ylab('Nº de genes anotados') + theme(axis.text.x=element_text(size = 10,
                                                                  angle=0),
                                               text = element_text(size=15),
                                         panel.grid.minor = element_blank(),
                                         panel.grid.major = element_blank(),
                                         axis.line.x = element_line(color="black"),
                                         axis.ticks = element_line(color="black")),
    # Interactions
    base_annotations = list(
        'Intersection size'=( 
            intersection_size(
              mapping=aes(fill="bars_color"),
              alpha = 0.2,
              color = "#90C432",
              width = 0.6, # Ancho barra
              text = list(
                vjust=0.5,
                hjust=-0.2,
                angle=90,
                size =4.5
            ), 
            text_colors=c(
                on_background='#878787', on_bar="#878787"
            )
            ) + scale_fill_manual(values=c("bars_color"="#90C432"), guide="none") +
              scale_alpha_manual(values = c(0.2))
            + theme(panel.grid.major = element_blank(), 
               panel.grid.minor = element_blank(),
               plot.background = element_rect(fill="transparent",
                                                   color = "transparent"),
          panel.background = element_rect(fill = "transparent",
                                          color = "transparent"),
          axis.line.y = element_line(color="black"),
          axis.text.y=element_text(size = 10, angle=0)
          #axis.line.x = element_line(color="black"),
          #axis.ticks = element_line(color="black")
          )
            + ylab('Anotaciones por grupo')
        ))
        
)  

UpsetPlot
```


### ORA {.tabset .tabset-fade -}   

#### GO  {.tabset .tabset-fade -}      

##### BP {-}  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_oraBP.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))]
Up = Up[lengths(Up) > 0]

# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))]
Down = Down[lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  

##### CC {-}  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_oraCC.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))][lengths(Up) > 0]
Up = Up[lengths(Up) > 0]

# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))]
Down = Down[lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  

##### MF {-}  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_oraMF.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))] 
Up = Up[lengths(Up) > 0]
# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))]
Down = Down[lengths(Down) > 0]
  
if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  


#### KEGG  {-}  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_oraKEGG.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))][lengths(Up) > 0]
Up = Up[lengths(Up) > 0]

# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))]
Down = Down[lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  


#### Reactome  {-}  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_oraReactome.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
Results2
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))]
Up = Up[lengths(Up) > 0]

# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))]
Down = Down[lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  




### GSEA {.tabset .tabset-fade -}  

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE}
# Prepare data
Data = sapply(Datas, function(x){
  geneList <- x$logFC
  names(geneList) <- as.character(row.names(x))
  geneList <- sort(geneList, decreasing = TRUE) 
  return(geneList)
  }, simplify = FALSE)  
contrasts = c("Ob - Np", "Ob.M - Np.M", "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
names(Data) = contrasts
```  

#### GO  {.tabset .tabset-fade -}      

##### BP {-} 

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_gseBP.RData")))
Results2 = sapply(Results, function(x)
  data.frame(x), simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){ 
  return(nrow(c))}
  , simplify = FALSE)

```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = "GSE",
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
lists = sapply(Results2, function(x) x$ID, simplify = FALSE)

if(length(lists)>1){RX_venn(lists, colors, names= NULL)} 

```  

##### CC {-}  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_gseCC.RData")))
Results2 = sapply(Results, function(x)
  data.frame(x), simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){ 
  return(nrow(c))}
  , simplify = FALSE)

```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = "GSE",
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}   
lists = sapply(Results2, function(x) x$ID, simplify = FALSE)

if(length(lists)>1){RX_venn(lists, colors, names= NULL)} 

```  

##### MF {-}  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_gseMF.RData")))
Results2 = sapply(Results, function(x)
  data.frame(x), simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){ 
  return(nrow(c))}
  , simplify = FALSE)

```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = "GSE",
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
lists = sapply(Results2, function(x) x$ID, simplify = FALSE)

if(length(lists)>1){RX_venn(lists, colors, names= NULL)} 

```  

#### KEGG  {-}  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_gseKEGG.RData")))
Results2 = sapply(Results, function(x)
  data.frame(x), simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){ 
  return(nrow(c))}
  , simplify = FALSE)

```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = "GSE",
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Order
ord = c("Ob.M - Np.M", "Ob - Np",  "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
colors = c( "Ob - Np" = "#884EA0",  "Ob.M - Np.M"  = "#2494B5" ,  
            "Ob.F - Np.F" = "#90C432" , "(Ob.M - Np.M) - (Ob.F-  Np.F)" = "#D8609A")
# Up
lists = sapply(Results2, function(x) x$ID, simplify = FALSE)

if(length(lists)>1){RX_venn(lists, colors, names= NULL)} 

```  

#### Reactome  {-}

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/Obesidad_gseReactome.RData")))
Results2 = sapply(Results, function(x)
  data.frame(x), simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){ 
  return(nrow(c))}
  , simplify = FALSE)

```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = "GSE",
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Order
ord = c("Ob.M - Np.M", "Ob - Np",  "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
colors = c( "Ob - Np" = "#884EA0",  "Ob.M - Np.M"  = "#2494B5" ,  
            "Ob.F - Np.F" = "#90C432" , "(Ob.M - Np.M) - (Ob.F-  Np.F)" = "#D8609A")
# Up
lists = sapply(Results2, function(x) x$ID, simplify = FALSE)

if(length(lists)>1){RX_venn(lists, colors, names= NULL)} 

```  
