---
title: "Resumen metaanálisis"
author: "Roxana Andreea Moldovan Moldovan"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: false
    toc_float: false
    number_sections: false 
    code_folding: hide
    theme: flatly
    bg: '#FFFFFF'
    fg: '#202020'
    primary: '#90C432'
    secondary: '#2494b5' 
  pdf_document:
    extra_dependencies: "subfig"
linkcolor: blue
urlcolor: blue
citecolor: blue
header-includes:
- \usepackage{subfig}
- \usepackage{float}
fig_caption: yes 
link-citations: TRUE

---

```{r setup, include=FALSE}
doAll = F
showAll = T
centrado = "center"
knitr::opts_chunk$set(echo = TRUE)
```

```{r echo=T, eval=TRUE, message=FALSE, warning=FALSE}
library(pacman)
pacman::p_load(clusterProfiler)
pacman::p_load(dplyr)
pacman::p_load(glue)
pacman::p_load(org.Hs.eg.db)
pacman::p_load(parallel)
pacman::p_load(ReactomePA)
pacman::p_load(stringr)

## Parametros
DirBase = "/home/rmoldovan/Metaanalisis"
DirBase = "C:/Users/roxya/OneDrive/Documentos/01Master_bioinformatica/00TFM/Git/T2D-Meta-Analysis"
DirData = glue("{DirBase}/Data")
DirPlots =  glue("{DirBase}/Plots")
DirOut = glue("{DirData}/ORA")

## Carga de funciones
#source(glue("{DirBase}/02Scripts/Functions.R"))

```

```{r echo=T, eval=TRUE, message=FALSE, warning=FALSE}
# Packages
pacman::p_load(flextable)
pacman::p_load(officer)
pacman::p_load(glue)
pacman::p_load(dplyr)
pacman::p_load(ggVennDiagram)
pacman::p_load(ggplot2)

# Function
# Output table
RX_table <- function(Data,
                     Color1 = "#007FA6",
                     Color2 = "#007FA6" ,
                     Color.l = "black" ,
                     Color.l2 = "#878787",
                     Color.up = "#CB326D",
                     Color.down = "#00AFBB",
                     footer = NULL,
                     font = "Calibri"){
  cols=colnames(Data)[-c(1)] # Columns with info
  col_keys = colnames(Data) # Nombres unicos de las columnas
  # Header
  header = data.frame(col_keys = col_keys,
                      H1 = c("", rep("Contraste", length(cols))),
                      H2 = c("", cols)
                      )
  
  ## Flextable
  # Set info
  ft <- flextable(Data, col_keys = colnames(Data))
  # Set header
  ft <- set_header_df(ft, mapping = header, key = "col_keys" )
  # Format number
  ft <- colformat_num(ft, big.mark = ".", decimal.mark = "," )
  # Set footer
  if(! is.null(footer)){
    ft <- add_footer(ft, values = footer) %>% 
      merge_h(part = "footer")  %>% 
      bold(j=1, part = "footer") %>%
      hline(border = fp_border(width = 2, color = Color1), part = "footer")
  }
  
  # Merge headers
  ft <- merge_h(ft, part = "header") %>% 
    merge_v( part = "header")
  
  # Merge contrastes
  #ft <- merge_v(ft, j = c(1,2), part = "body")
  
  # Horizontal lines
  'ft <- hline(ft, i=seq(from=3, to=nrow(Data), by=3),
              border = fp_border(width = 1, color = Color.l2), part="body")'
  ft <- hline(ft,border = fp_border(width = 2, color = Color1), part = "header")
  
  # Outer bottom
  ft <- hline_bottom(ft, border = fp_border(width = 2, color = Color1))
  
  # Alineamiento
  ft <- flextable::align(ft, i=1, align = "center", part = "header") %>%
    flextable::align(i=2, align = "right", part = "header")
  ft <- flextable::align(ft, align = "right", part = "footer")
  ft <- flextable::align(ft, j=1, align = "left", part = "footer")
  
  
  # Header design
  ft <- fontsize(ft, i = 1:2, size = 12, part = "header") %>%
    color(i=1, color = Color2, part = "header") %>%
    color(i=2, color = Color.l2, part = "header") %>%
    bold(i=1, bold = TRUE, part = "header")
  # Rotate names
  #ft <- rotate(ft, i = 2, rotation = "btlr", part = "header", align = "bottom")
  
  # Font
  #font(ft, fontname = font, part = "all")
  
  # Matriz de colores
  colormatrix <- ifelse(Data[, cols] == 0, Color.l2, Color.l )
  # Color
  ft <- color(ft, j=cols, color = colormatrix, part = "body") 
  # Color
  x = Data[, 1]
  colors = case_when(
    x == "Up" ~ Color.up,
    x == "Down" ~ Color.down,
    TRUE ~ Color.l
  )
  ft <- color(ft, j=1, color = colors, part = "body") %>%
    bold(j=1, bold = TRUE, part = "body")

  return(ft)
}


RX_venn <- function(lists, colors, names){
  venn <- Venn(lists)
  d <- process_data(venn)
  d2 <- process_data(venn)
  
  d2@region <- st_polygonize(d@setEdge) 
  ggplot() +
  geom_sf(aes(fill = name), data = venn_region(d2)) +
  geom_sf(#aes(color = name), 
    size = 4, color = "grey",
    data = venn_setedge(d))  +
  geom_sf_text(aes(label = count), data = venn_region(d)) +
  scale_fill_manual(values = alpha(colors, .3)) +
  theme_void() +  # Tema
        theme(plot.background = element_rect(fill="transparent", color="transparent"),
              panel.background = element_rect(fill = "transparent", color="transparent"),
              axis.line = element_line(colour = "transparent")) +
    guides(fill = guide_legend(title = "Contrastes",
                                order = 1)) +
  if(! is.null(names)){
      geom_sf_text(aes(label = name), data = venn_setlabel(d), nudge_x = -0.1, nudge_y = -0.1) 
  }
  } 
```  


## Obesidad {.tabset .tabset-fade -}   

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE}
DirData = "C:/Users/roxya/OneDrive/Documentos/01Master_bioinformatica/00TFM/Git/T2D-Meta-Analysis/Data/MA/Obesity"

f= c("ObvsNp/Meta-analysis_1_DF.RData", 
     "ObMvsNpM/Meta-analysis_2_DF.RData",
     "ObFvsNpF/Meta-analysis_3_DF.RData",
     "ObM_NpMvsObF_NpF/Meta-analysis_4_DF.RData")

files = glue("{DirData}/{f}")
```


### Obesidad {.tabset .tabset-fade -}  

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE}
# Prepare data
Datas = sapply(files, function(x) get(load(file=x)), simplify = FALSE)
p_lim = 0.05
logFC_lim = 0

# Gene lists
Direction = c("Up", "Down")

Data = sapply(Datas, function(Data){
  Up = rownames(Data[which(Data$p.adjust.BH < p_lim & Data$logFC > logFC_lim), ])
  Down = rownames(Data[which(Data$p.adjust.BH < p_lim & Data$logFC < 0), ])
  return(c("Up" = list(Up), "Down" = list(Down)))
}, simplify = FALSE)

contrasts = c("Ob - Np", "Ob.M - Np.M", "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
names(Data) = contrasts
```  

#### GO  {.tabset .tabset-fade -}      

##### BP {-}

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE} 
# Realiza el análisis de enriquecimiento funcional
Results = mclapply(contrasts, function(c){
  r = sapply(Data[[c]], function(x){
    enrich_result <- enrichGO(gene          = x,
                              OrgDb         = org.Hs.eg.db,  
                              keyType       = "ENTREZID",  
                              ont           = "BP", 
                              pAdjustMethod = "BH",  
                              pvalueCutoff  = 0.05,  
                              qvalueCutoff  = 0.05)
    return(enrich_result)}, simplify = FALSE, USE.NAMES = TRUE)
  return(r)
})
Results = setNames(Results, contrasts) 

save(Results, file=glue("{DirOut}/ObesidadBP.RData"))
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/ObesidadBP.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Order
ord = c("Ob.M - Np.M", "Ob - Np",  "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
colors = c( "Ob - Np" = "#884EA0",  "Ob.M - Np.M"  = "#2494B5" ,  
            "Ob.F - Np.F" = "#90C432" , "(Ob.M - Np.M) - (Ob.F-  Np.F)" = "#D8609A")
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))][lengths(Up) > 0]
# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))][lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  

##### CC {-}

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE} 
# Realiza el análisis de enriquecimiento funcional
Results = mclapply(contrasts, function(c){
  r = sapply(Data[[c]], function(x){
    enrich_result <- enrichGO(gene          = x,
                              OrgDb         = org.Hs.eg.db,  
                              keyType       = "ENTREZID",  
                              ont           = "CC", 
                              pAdjustMethod = "BH",  
                              pvalueCutoff  = 0.05,  
                              qvalueCutoff  = 0.05)
    return(enrich_result)}, simplify = FALSE, USE.NAMES = TRUE)
  return(r)
})
Results = setNames(Results, contrasts) 

save(Results, file=glue("{DirOut}/ObesidadCC.RData"))
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/ObesidadCC.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Order
ord = c("Ob.M - Np.M", "Ob - Np",  "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
colors = c( "Ob - Np" = "#884EA0",  "Ob.M - Np.M"  = "#2494B5" ,  
            "Ob.F - Np.F" = "#90C432" , "(Ob.M - Np.M) - (Ob.F-  Np.F)" = "#D8609A")
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))][lengths(Up) > 0]
# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))][lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  

##### MF {-}

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE} 
# Realiza el análisis de enriquecimiento funcional
Results = mclapply(contrasts, function(c){
  r = sapply(Data[[c]], function(x){
    enrich_result <- enrichGO(gene          = x,
                              OrgDb         = org.Hs.eg.db,  
                              keyType       = "ENTREZID",  
                              ont           = "MF", 
                              pAdjustMethod = "BH",  
                              pvalueCutoff  = 0.05,  
                              qvalueCutoff  = 0.05)
    return(enrich_result)}, simplify = FALSE, USE.NAMES = TRUE)
  return(r)
})
Results = setNames(Results, contrasts) 

save(Results, file=glue("{DirOut}/ObesidadMF.RData"))
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/ObesidadMF.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Order
ord = c("Ob.M - Np.M", "Ob - Np",  "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
colors = c( "Ob - Np" = "#884EA0",  "Ob.M - Np.M"  = "#2494B5" ,  
            "Ob.F - Np.F" = "#90C432" , "(Ob.M - Np.M) - (Ob.F-  Np.F)" = "#D8609A")
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))][lengths(Up) > 0]
# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))][lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  


#### KEGG  {-}

```{r echo=doAll, eval=TRUE, message=FALSE, warning=FALSE} 
# Realiza el análisis de enriquecimiento funcional
Results = mclapply(contrasts, function(c){
  r = sapply(Data[[c]], function(x){
    enrich_result <- enrichKEGG(gene          = x,
                                organism      = "hsa",  
                                keyType       = "ncbi-geneid",
                                pAdjustMethod = "BH",  
                                pvalueCutoff  = 0.05,  
                                qvalueCutoff  = 0.05)
    return(enrich_result)}, simplify = FALSE, USE.NAMES = TRUE)
  return(r)
})
Results = setNames(Results, contrasts) 

save(Results, file=glue("{DirOut}/ObesidadKEGG.RData"))
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
# Get data
Results = get(load(glue("{DirOut}/ObesidadKEGG.RData")))
Results2 = sapply(Results, function(c)
  sapply(c, function(x) data.frame(x), simplify = FALSE)
  , simplify = FALSE)
# Recuento
Res = sapply(Results2, function(c){
  dim = sapply(c, function(x) nrow(x), simplify = TRUE)
  return(c(dim, Total = sum(dim)))}
  , simplify = FALSE)
```  

```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}
DT = data.frame(Contraste = names(Res[[1]]),
                  Res, check.names = FALSE)
#footer = c("Nº total de genes", sapply(Datas, function(x) nrow(x)))
col_keys = colnames(DT)
RX_table(DT) %>% flextable::width( width = 1.2, unit = "in")
```  


```{r echo=showAll, eval=TRUE, message=FALSE, warning=FALSE}  
# Order
ord = c("Ob.M - Np.M", "Ob - Np",  "Ob.F - Np.F", "(Ob.M - Np.M) - (Ob.F-  Np.F)")
colors = c( "Ob - Np" = "#884EA0",  "Ob.M - Np.M"  = "#2494B5" ,  
            "Ob.F - Np.F" = "#90C432" , "(Ob.M - Np.M) - (Ob.F-  Np.F)" = "#D8609A")
# Up
Up = sapply(Results2, function(x) x$Up$ID, simplify = FALSE)
Up = Up[match(ord, names(Up))][lengths(Up) > 0]
# Down
Down = sapply(Results2, function(x) x$Down$ID, simplify = FALSE)
Down = Down[match(ord, names(Down))][lengths(Down) > 0]

if(length(Up)>1){RX_venn(Up, colors, names= NULL)}
if(length(Down)>1){RX_venn(Down, colors, name=NULL)}

```  

